[workspace]
members = ["world", "shader"]

[package]
name = "cuneus-simulations"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
hashbrown = {version="0.17.1"}
glam = {version="0.33.2", features=["bytemuck"]}
bytemuck = { version = "1", features = ["derive"] }
anyhow = "*"
log = {version = "*", features=["std","release_max_level_info", "max_level_trace"] }


[dependencies]
cuneus = {path="cuneus", default-features = false}
pico-args = "0.5.0"
world = {path = "./world"}
hashbrown = {workspace=true}
glam = {workspace=true}
bytemuck = {workspace=true}
log = {workspace=true}


[profile.dev.package.world]
opt-level = 3

[build-dependencies]
wesl = "0.4.0"
spirv-builder = {git = "https://github.com/Rust-GPU/rust-gpu.git"}

# Compile build-dependencies in release mode with
# the same settings as regular dependencies.
[profile.release.build-override]
opt-level = 3
codegen-units = 16
[profile.dev.build-override]
opt-level = 3



[profile.flamegraph]
inherits = "release"
debug = true

